name: Update file manifest for turtles

on:
  push:
    branches: [dev]

jobs:
  update-manifest:
    name: Update manifest file
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: generate manifest
        run: |
          rm manifest.txt
          for filename in src/*.lua; do
            echo $filename >> manifest.txt
          done

      - name: publish manifest artifact
        run: |
          git add .;
          git commit -m "update manifest";
          git push origin HEAD:master
