name: Update file manifest for turtles

on:
  push:
    branches: [dev]

jobs:
  update-manifest:
    name: Update manifest file
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: generate manifest
        run: |
          rm manifest.txt
          for filename in src/*.lua; do
            echo "${filename##*/}" >> manifest.txt
          done

      - name: setup github commit
        run: |
          git config --global user.email "dylan.brookes10@gmail.com";
          git config --global user.name "Dylan Brookes";
      - name: publish manifest artifact
        run: |
          git add .;
          git commit -m "update manifest";
          git pull --rebase;
          git push -f origin dev:main;
