name: Update file manifest for turtles

on:
  push:
    branches: [main]

jobs:
  update-manifest:
    name: Update manifest file and publish transpiled lua
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build lua files from typescript
        run: |
          rm -r build
          npm ci;
          npm run build;

      - name: generate manifest
        run: |
          rm manifest.txt
          for FILE in $(find ./build -name "*.lua")
          do
            echo "${FILE:1}" >> manifest.txt
          done

      - name: setup github commit
        run: |
          git config --global user.email "dylan.brookes10@gmail.com";
          git config --global user.name "Dylan Brookes";
      - name: publish manifest artifact
        run: |
          git add .;
          git commit -m "update manifest";
          git pull --rebase;
          git push -f origin;
