name: Update file manifest for turtles

on:
  push:
    branches: [main]

jobs:
  update-manifest:
    name: Update manifest file
    runs-on: ubuntu-latest

    steps:
      - name: manifest update
        run: |
          echo "" > manifest.txt
          for filename in src/*.lua; do
            echo $filename >> manifest.txt
          done
