name: Update file manifest for turtles

on:
  push:
    branches: [main]

jobs:
  update-manifest:
    name: Update manifest file
    runs-on: ubuntu-latest

    steps:
      - name: generate manifest
        run: |
          echo "" > manifest.txt
          for filename in src/*.lua; do
            echo $filename >> manifest.txt
          done

      - name: publish manifest artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: manifest.txt
